CREATE TABLE TRANSACTIONS
(
    TRANSACTION_ID      INT AUTO_INCREMENT PRIMARY KEY,
    TITLE               NVARCHAR(250) NOT NULL,
    PUBLICATION_DATE    DATE          NOT NULL,
    AMOUNT              DECIMAL         NOT NULL
);